import csv
import os
import pandas as pd
from torchvision.io import read_image
from torch.utils.data import Dataset
import torch
from ast import literal_eval
import re
import numpy as np

def extract_number(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')


def extract_index(string):
    return string.split('_')[0:2]

# Works for strucure of type
# Phase2/Data/Train
# PA
# 1_1A.jpg
# 1_2A.jpg
# 2_1A.jpg
# 2_2A.jpg
# .
# .
# PB
# 1_1B.jpg
# 1_2B.jpg
# 2_1B.jpg
# 2_2B.jpg
# .
# .

# img_dir includes ending //
class CustomImageDataset(Dataset):
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        self.Hs = pd.read_csv(annotations_file)
        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform

        image_files = [str(img_dir + "PA//" + f) for f in os.listdir(img_dir + "PA\\") if f.endswith(".jpg")]
        self.img_paths1 = sorted(image_files, key=extract_number)
        image_files = [str(img_dir + "PB//" + f) for f in os.listdir(img_dir + "PB\\") if f.endswith(".jpg")]
        self.img_paths2 = sorted(image_files, key=extract_number)

    def __len__(self):
        return len(self.Hs)

    def __getitem__(self, idx):
        pa_path = self.img_paths1[idx]
        pb_path = self.img_paths2[idx]

        PA = read_image(pa_path)
        PB = read_image(pb_path)
        H = torch.tensor(self.Hs.iloc[idx].tolist())
        # Add transformation code if required

        return PA, PB, H


class UnsupervisedDataSet(Dataset):
    def __init__(self, data_dir="../Data/", test=False, transform=None, target_transform=None):
        """
        Assumes the file structure:
        Phase2:
            - Code:
                - CustomImageDataset.py
            - Data:
                -GenTrain:
                    -Original
                    -Warped
                    -CSV
                -GenTrain:
                    -ibid.
                -Train
                -Test
        Modify this to use a different data set than the one generated by MakeData.ipynb

        The unsupervised network needs the Pa-Pb pair, the ground truth homography H and the whole origianl image Ca
        """
        if test:
            sub_dir = os.path.join(data_dir, "GenTest")
        else:
            sub_dir = os.path.join(data_dir, "GenTrain")

        self.data_dir = data_dir
        self.transform = transform
        self.target_transform = target_transform


        pa_path = os.path.join(sub_dir, "Original/")
        # Path to the warped sample
        pb_path = os.path.join(sub_dir, "Warped/")

        # path to the whole unwarped image
        self.ca_path = os.path.join(data_dir, "Test/" if test else "Train/")

        self.pa_imgs = sorted([str(pa_path + f) for f in os.listdir(pa_path)], key=extract_index)
        self.pb_imgs = sorted([str(pb_path + f) for f in os.listdir(pb_path)], key=extract_index)
        self.ca_imgs = sorted([str(self.ca_path + f) for f in os.listdir(self.ca_path)], key=extract_number)

    def __len__(self):
        return len(self.Hs)

    def __getitem__(self, idx):

        ca_path = self.ca_imgs[idx]
        # modify this to match the 10 samples per image
        idx *= 10
        pa_path = self.pa_imgs[idx:idx + 10]
        pb_path = self.pb_imgs[idx:idx + 10]

        PA = torch.stack([read_image(pa) for pa in pa_path])
        PB = torch.stack([read_image(pb) for pb in pb_path])
        CA = read_image(ca_path)


        return PA, PB, CA
